version: '3.9'

services:

  mocker:
    container_name: mocker
    build: ./mocker-service
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./mocker-service/app:/app
    ports:
      - 8000:8000

  # nginx:
  #   container_name: nginx
  #   build: ./nginx
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - mocker

